spring.application.name=KnowSphere

server.port=8081

####DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5434/knowspheredb
spring.datasource.username=Arjun
spring.datasource.password=dummy

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


###OPEN AI CONFIGURATION

spring.ai.openai.api-key=${OPENAI_API_KEY:demo-key}
spring.ai.openai.chat.temperature=0.2
spring.ai.openai.embedding.model=text-embedding-3-small

spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.table-name=vector_store
spring.ai.vectorstore.pgvector.schema-name=public
spring.ai.vectorstore.pgvector.initialize-schema=true

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=50MB

###APP CONFIGURATIONS
app.rag.chunk-size=700
app.rag.chunk-overlap=100
app.rag.top-k=5
app.rag.similarity-threshold=0.0

app.cors.allowed-origins=*
app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
app.cors.allowed-headers=*
